---

- hosts: localhost
  connection: local
  gather_facts: no
  become: yes
  vars:
     ansible_python_interpreter: '{{ ansible_playbook_python }}'
  tasks:




   - name: loop over role
     include_role: 
       name: approle
     vars:
       cluster: "{{ item }}"
     with_items: "{{ clusters }}"      
