---


   - name: choose context
     shell:
       cmd:  kubectl config use-context "{{ cluster }}"-admin@{{ cluster }}

   - name: Delete avi-system namespace
     shell:
       cmd: kubectl delete ns avi-system
     
   - name: Delete gslb-members
     shell:
       cmd: rm -rf gslb-members 

   - name: Remove deployment/service
     shell:
       cmd: kubectl delete -f /home/chris/ansible/hack.yaml      

